language: csharp
mono: none
dotnet: 2.1.105
solution: CitadelCore.sln
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: W/LY3gMg/UVABa8tho3KJ/nOt94KZZokb7dYgKMaiu9It1I2ns9J1LayMMdI23wDs8UKjUNEoDgVGZhhgaFN+fJA6vYKkUpKV/DZBDZlSFKJhiLuChP5TEQ3RSJOqzkhARN1TyLDBbLZ6DNYTVHsT27YtLurKKqQFUZnwXRC+x/z+1e2kaYeztggxLwKcpuKf2FQEwVSVHipMtdaIMkK2sVkcTsgsu7kl0Q6W/05EJKipVtMrxCPHeLONZ0QygXeXoYx9VaTAL2B9A9nTmwBhquc7Tess15cW8EF723WZjMO9iPEnqnbMWrmC3mfOw8IA/SJ/fWyW6gcLOXkuA9VWpt5EIQTc39H41D2ugAEPkkHD11J65UPY2mlThKfoPajjzhG6Jh91JQPoB1qQrSNIpTgm5PrkYdrA6zRkiJIGFwGhJKnL5tGvs9wvVf/rrp4qu+q16at0+K+xNsNP6CQ+Rcr98zyh7AOEMa/sJvV9KaU5SoRSVEU6oFEuC4Nq33s3qAzvZyMn6Co6FARmRoR9lGnBz6xdz1Q9iIwGpKSfFoABYQUVZmMWqKB6ARSiNTiywvMp5SsxMgf0asfc1kE49uRXYwf1kGvtWBB7FC2i8tevnIvFcGWLfhKrICluvC6hHLN8ezxytV3Y6mp70/jYoq8bHOfkZtshWmJuLHkCGE=

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "TechnikEmpire/CitadelCore"
      description: ".NET proxy server core logic."
    notification_email: info@technikempire.com
    build_command_prepend: "dotnet clean"
    build_command: "dotnet build --configuration Release"
    branch_pattern: coverity_scan

script: dotnet clean && dotnet build --configuration Release
