language: csharp
mono: none
dotnet: 2.1.105
solution: CitadelCore.sln
script: dotnet clean && dotnet build --configuration Release
env:
  global:
    secure: vZ64z6nQtqW7IjTJv5+g4mRW2FfntZIslAxWYVZfugUkssinqkvJ6xtTTvgXu3mynZel06hxvCclpoI4xqVsZWRhjbmaLR/hsvlosJ3SOUJxaxUhh/jpUehNz42sLwg+4WcQDRTsJbqP2t4NHcsB3+S9mw6vK6tuROoVekcwVLuMbJCYu4HOPe+V/7/laUwXbZatCg9Kcsc0+NJF6K5fhW0d4fF78p5DhBZ42IKJzfzleJb5G37zZ1M/ZKyvbW40GkkmpYrj7QwvDGuWtKwb2E8LFvO8V+jfHSpw8jnZ9RThDnhVbSTtv1jHvNuAESrdOcfBQQ4QlE0zOJx7T3Dys1SePP7zRQ3q8IFr7w2WgVmYFgdlgXTmCdAWpVfwTXJ6bUa2E7XnrNnDuvmFOO7qnBwM5yEYBAnAX7wDA9Q2JGfKQ6krUnjcvmcLpOqOumagqWg3OMfb3FyUB+hkx11Gv+JFvEyURC/MNnD9JLS8xomcPTd32ObgFk9y7zQ6YLJqSscaxbxgrtdIRWEm8Bv74B3KalrI4IK0iYrpoKjk18vkK0K4qrGn0RuHSxgcRZTpxK5BdFbEvGm8b3UOgM/BTWjZNx5Ruh6SnDTgwJuAAenrIbW6yKgWmaRXbwZCJyQSZ1z/kSMEKi3BNVPfFtQYQR6Vs9qfgIZJzV6KMV3AITM=
before_install:
- echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN
  CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
addons:
  coverity_scan:
    project:
      name: TechnikEmpire/CitadelCore
      description: ".NET proxy server core logic."
    notification_email: info@technikempire.com
    build_command_prepend: dotnet clean
    build_command: dotnet build --configuration Release
    branch_pattern: coverity_scan
