language: csharp
mono: none
dotnet: 2.1.105
solution: CitadelCore.sln
script: dotnet clean && dotnet build --configuration Release
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "jm5MumM78sQJIRyihrWUueP9AuHJeE8vbNQIN88QHQ1XdvPy+q+wDrIFkeF0BmCOcU6EjaVbSUpRTC47r9OtJ64jo0kcpj2qWu8QOIcEVjYtbjPpEF4FE+TmZJFFrUi6E3akXe1Tr3ZB97Q2WkB2P2zIIAHLXST7JPcEaIzQdSHEBzNZ3Zgj5Z9oROXv2WnMtHpNRDk644r6RI2ElotcxIKGgFnVo3nkS4fJkgWwnuaqVykvMltxl2n65BYqHkOtTu3fT3KpC/mp/tUH/lFvbCG2Y3A+D3Ag8CJAXHcPllN+mc2mRfRGrh+GsjcHfWwPEU7knUMdsj5fAuPW+yqLQr7m4ebDaQzLHTAAZboeUhQJ3CP2GtfJilcxIdaom0a+1h7SP4Ik/mv68ICR0/6OfuEc8I/zbJtml6+DXElBBZE07P2GHMHHJXqX4rfm5eGdRwpWutUoFpc3/s6QWSA2uJku5QbqpevQjgEgQnkM3dMTiJm89Df1RtzRGVizTouYevanPwiZKQfywdrewB7uKZzT8pVXRQNPRKwfygsrOK2W+Jd2WgCWxcBcZN8Fhv1aL5PIzSL99U9QhHnnrcV30yOx8YtsfFj8DuoxpZVpOisKXko8UxJZTUuoLmart5eUcFEzOcSVtdyrt7R8022i3Ja6H7AxDOX5tT9VTcaoQBc="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "TechnikEmpire/CitadelCore"
      description: ".NET proxy server core logic."
    notification_email: info@technikempire.com
    build_command_prepend: "dotnet clean"
    build_command: "dotnet build --configuration Release"
    branch_pattern: coverity_scan
